version: '3.1'

services:
  app:
    build: .

  db:
    build: db/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  react-app:
    build: react-app/.
    ports:
      - "8080:80"



