name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@v2.0
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "${{ secrets.ORG_NAME }}"
          ado_project: "${{ secrets.PROJ_NAME }}"
          ado_area_path: "${{ secrets.PROJ_NAME }}"
          ado_iteration_path: "${{ secrets.PROJ_NAME }}"
          ado_wit: "User Story"
          ado_new_state: "To Do"
          ado_active_state: "Doing"
          ado_close_state: "Done"
          ado_bypassrules: true
          log_level: 100
