name: A workflow for coursework
on: push

jobs:
  build:
    name: CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn package
      - name: Docker compose
        run: docker-compose up --abort-on-container-exit