name: Push workflow
on: push

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.SET08103.cw.UnitTests test

  integration:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Integration Tests
        run: | 
          docker build -t database ./db
          docker run --name world -dp 3306:3306 database
          mvn -Dtest=com.SET08103.cw.UnitTests test
          mvn -Dtest=com.SET08103.cw.IntegrationTests test
          docker stop world
          docker rm world
          docker image rm database
          mvn surefire-report:report-only
      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          directory: ./target/site/jacoco
          flags: Integration Tests
          verbose: true

  build:
    name: Docker CI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn package -DskipTests
      - name: Docker compose
        run: docker-compose -f docker-compose-ci.yml up --abort-on-container-exit